### PR TITLE
Examples

### PR DESCRIPTION
**Pull request by ErinsMatthew**
1. Added additional options to <flyout-navigation> to allow for customization.
- `tolerance {Integer} (optional)` - how much tolerance to allow when user is entering submenu (default: 500)
- `delay {Integer} (optional)` - how long (in milliseconds) to wait when user is entering submenu (default: 1000)
- `direction {String} (optional)` - the direction of the submenu (right, left, below, above) (default: right)
- `enter {Function} (optional)` - callback to execute when row is entered (default: set menu height)
- `exit {Function} (optional)` - callback to execute when row is exited (default: nothing)
- `activate {Function} (optional)` - callback to execute when row is activated (default: set menu height)
- `deactivate {Function} (optional)` - callback to execute when row is deactivated (default: nothing)
- `exitmenu {Function} (optional)` - callback to execute when user exits the menu (default: close menu)
1. Added additional examples.

### CODE REVIEW

**Comment by neilff** [comment]
Am I missing something on the e-commerce demo? It looks incomplete

**Comment by ErinsMatthew** [comment]
You're right.  I meant to expand on it.  I will push an update to it.

**Comment by ErinsMatthew** [comment]
I've expanded on the eCommerce example.  Thank you.

**Comment by neilff** [comment]
:+1:

**Pull request merged**
